spring:
  data:
    mongodb:
      # In Case of mongodb Repel Set
      #uri: mongodb://${MONGO_DB_HOSTNAME}:${MONGO_DB_PASSWORD}@mongod-0.mongodb:27017,mongod-1.mongodb:27017,mongod-2.mongodb:27017/users
      host: admin
      port: 27017
      username: devdb
      password: devdb123
      database: mydb
      authentication-database: admin

server:
  port: 27017
